### ISSUE TITLE
Style Guide Doc

### ISSUE THREAD

**Issue by gold-mari** [GDACollab/TacoCat#12]
Make a style guide for all the music and SFX in Taco Cat.
[Example doc from last year!](https://docs.google.com/document/d/1R6MSar4RCfwd4tGXtrEZLRV839RCwHPDHD3Fb91u4Ho/edit)

**Comment by vinhta1** [comment]
https://docs.google.com/document/d/1R2i_TjMr9fab4DJrdDIlw2lI8va4kjZ0dWQUF1NP3CM/edit?usp=sharing
