### ISSUE TITLE
Story Music Final Asset Development

### ISSUE THREAD

**Issue by JeremyH0451** [GDACollab/TacoCat#200]
Polish and further develop the music tracks for the story cutscenes in the game based on the pre-existing concept tracks.

- Calm, always slow?
- Acoustic guitar focused, if not just acoustic guitar.
- Happy Ending and Sad Ending

Concept tracks found here: [https://drive.google.com/drive/folders/19Bh9JJDRxfDxpQUo80LbBDfit7WdMZE3?usp=share_link](https://drive.google.com/drive/folders/19Bh9JJDRxfDxpQUo80LbBDfit7WdMZE3?usp=share_link)

**Comment by vinhta1** [comment]
made a happy ending: https://discord.com/channels/1050526588514598942/1073492504604839956/1105725180946423808

**Comment by Irkedibis** [comment]
For Texting Cutscenes:
Uploaded "[mus_It'sFromJamie2_JacksonRichmond](https://drive.google.com/file/d/1f-rcnDQ0MYDDOUNXgPfNGBF-3oCwsdWW/view?usp=share_link)"
