### ISSUE TITLE
SFX Concepts (UI and Menus)

### ISSUE THREAD

**Issue by JeremyH0451** [GDACollab/TacoCat#201]
SFX for the UI and menu assets.

- Select
- Backtrack
- Button Hover
- Scene Start/Stop

**Comment by Irkedibis** [comment]
https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=sharing

Added

- Select | "sfx_Type02_JacksonRichmond"
- Button Hover | "sfx_UIHover_JacksonRichmond"
