### ISSUE TITLE
Music Concepts (Story, Good Ending)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#210]
[Story Cutscene Music Drive Folder](https://drive.google.com/drive/folders/19Bh9JJDRxfDxpQUo80LbBDfit7WdMZE3?usp=share_link)

Take the concept track "[TacoCatIdea003](https://drive.google.com/drive/folders/1syITvc-lLpP4G_qgPipvK8oF4mGzudAT?usp=share_link)" and re-instrumentalize it for the **good ending of the game**

Please put the music track in the drive folder linked above, and post a comment below with the name and google drive link of your song!

**Comment by vinhta1** [comment]
made a happy ending: https://discord.com/channels/1050526588514598942/1073492504604839956/1105725180946423808

**Comment by vinhta1** [comment]
[Added a new version to the drive](https://drive.google.com/file/d/1O8t4h3CXMKONdS0N6fQkiTnUPRUh40eb/view?usp=sharing)
Working title: "Until Next Time"

**Comment by vinhta1** [comment]
[Semi-final](https://drive.google.com/file/d/1f-rcnDQ0MYDDOUNXgPfNGBF-3oCwsdWW/view?usp=sharing)
