### ISSUE TITLE
Car Engine RPM

### ISSUE THREAD

**Issue by JeremyH0451** [GDACollab/TacoCat#235]
Driving SFX Folder: https://drive.google.com/drive/folders/18LJnK-7HCsLu2p1BKaGfPW0A_So0qr5f?usp=share_link
SFX Checklist: https://docs.google.com/spreadsheets/d/1p6o-WQsl1Hy2EW_-neKIY4pfV3HE_lr5xGYMFvKN7fs/edit?usp=sharing

Please give us a variety of ~10 second clips of stagnant car audio, ranging from humming to absolute REVVING. We can create the fluid transitions between them using FMOD.

Please upload your asset(s) into the Driving SFX folder, leave a comment below linking to the folder, along with the name of the asset(s) you uploaded

**Comment by Irkedibis** [comment]
Here's the folder of engine sounds made by Jeremy and Jackson:
https://drive.google.com/drive/folders/1fvhXFZDBgN_YTCi8scM3LMuflRt14Wpo?usp=share_link
