### ISSUE TITLE
UI Backtrack SFX

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#238]
UI & Menu SFX Folder: https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=sharing
SFX Checklist: https://docs.google.com/spreadsheets/d/1p6o-WQsl1Hy2EW_-neKIY4pfV3HE_lr5xGYMFvKN7fs/edit?usp=sharing

Please create a simple, almost invisible sound equivalent to a click. This is for when the player presses ESC to leave menus and get back into the game.

Please upload your asset(s) into the UI & Menu SFX folder, leave a comment below linking to the folder, along with the name of the asset(s) you uploaded

**Comment by JeremyH0451** [comment]
Simple click sound for a backtrack sfx. 
[https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link](https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link)

**Comment by JeremyH0451** [comment]
Hopefully you can hear this backtrack sound now. "sfx_UI_Backtrack_JeremyHahnandVinhTa_V2.wav"
[https://drive.google.com/file/d/10yftQKpWpud3ZCJJhPBjh4P7iSZ1EFOl/view?usp=share_link](https://drive.google.com/file/d/10yftQKpWpud3ZCJJhPBjh4P7iSZ1EFOl/view?usp=share_link)
