### ISSUE TITLE
[ADDITION][Taco] Taco Auto-Sub Timer

### ISSUE THREAD

**Issue by itspebbleboy** [GDACollab/TacoCat#243]
After a new order is displayed, start a timer (of variable length). when the timer expires the taco should be auto submitted.

What this means is that Alex should finish putting the ingredient they have in their paw on the taco and then the taco should get submitted automatically.

This timer will also get shorter as the game progresses (needs to be related to Level int

**Comment by skysfalling** [comment]
Scoped out of project
