### ISSUE TITLE
[ADDITION][Driving] No Gas But Still Nitro Indicator

### ISSUE THREAD

**Issue by itspebbleboy** [GDACollab/TacoCat#245]
if gas==0 but nitro !=0 
display text on the screen saying "Use your Nitro!" next to the nitro indicator

**Comment by Shinoyhe** [comment]
Finished. 5/4/23
Branch: `NitroIndicatior-EthanY`
- Ethan Y

**Comment by skysfalling** [comment]
copied into master, used temp assets. I have an idea for an artistic style for this task. If I don't get to concepting it before this Friday, ask me about what I think at the workjam so we can talk to art about it.
