### ISSUE TITLE
Sign Drops Down and Hangs (Menu)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#273]
UI & Menu SFX Folder: https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link

After you complete the game once, in the menu a _mysterious_ sign falls from the sky, suspended by rope, and bounces(?) into frame. **Please make this ~1 second abstract sound of a sign dropping down**

Please upload your asset(s) into the Main Menu SFX folder, and leave a comment with the name and link to that/those asset(s)

**Comment by sweetautumndeer** [comment]
Sign Drops and Hangs SFX: https://drive.google.com/file/d/1rS9arKzL4YenYuG_Df6WqtGv8GqZELYH/view?usp=sharing
