### ISSUE TITLE
Convert .wav into .mp3 (EVERYTHING)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#274]
please please please please 🙏 

Pick an [SFX folder in the google drive](https://drive.google.com/drive/folders/18oIyb29iZD8vlwA71ZmPFmUEJQZt9grA?usp=share_link) and replace all the SFX as their .mp3 files

Due by Sunday 5/14 @11:59pm!!!

**Comment by jwdicker** [comment]
Created new folder for new mp3 sounds called "_mp3 Versions"
https://drive.google.com/drive/folders/1TIEi835gFqXlJS8JEwWUCfYgcqbaQtDG?usp=share_link

**Comment by jwdicker** [comment]
Moved "sfx_CarLandConcept2_JacobDickerman.mp3", "SFX_Crash sound affect_David_Louis_Carroll.mp3", and "sfx_Crickets_JacksonRichmond.mp3" to the mp3 folder.

**Comment by JeremyH0451** [comment]
Converted the files from the driving folder to mp3
[https://drive.google.com/drive/folders/1TIEi835gFqXlJS8JEwWUCfYgcqbaQtDG?usp=share_link](https://drive.google.com/drive/folders/1TIEi835gFqXlJS8JEwWUCfYgcqbaQtDG?usp=share_link)

**Comment by jwdicker** [comment]
Beat me to the punch!

**Comment by jwdicker** [comment]
Created new "Uncompressed Originals" folders for the "gimmegimmegimme  🐱 (File responses)", "Story", "Taco Making", and "UI & Menu" folders.

**Comment by jwdicker** [comment]
Converted the files from the Story folder to mp3
https://drive.google.com/file/d/13ayhY3hWwgBmBCgr9ZmrpkgNPs2k13Rg/view?usp=share_link

**Comment by JeremyH0451** [comment]
Finished UI sfx
[https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link](https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link)
