### ISSUE TITLE
Refine Sheep SFX (Taco Making)

### ISSUE THREAD

**Issue by itspebbleboy** [GDACollab/TacoCat#277]
Folder: https://drive.google.com/drive/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j?usp=share_link

sheep is goth, make pitch lower

SUBMIT AS MP3

**Comment by cigreen** [comment]
https://drive.google.com/drive/u/2/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j

Added 4 new sheep sounds (2 Sheep Happy, 2 Sheep Unhappy) to better fit the goth sheep.
