### ISSUE TITLE
Refine Bird SFX (Taco Making)

### ISSUE THREAD

**Issue by itspebbleboy** [GDACollab/TacoCat#278]
Raven, lower the pitch, too high

**Comment by Irkedibis** [comment]
Customer SFX folder: https://drive.google.com/drive/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j?usp=share_link

Added:

- sfx_BirdBadReact3.1_AnnieZhang
- sfx_BirdBadReact4.1_AnnieZhang
- sfx_BirdGoodReact3.1_AnnieZhang
- sfx_BirdGoodReact4.1_AnnieZhang

**Comment by Irkedibis** [comment]
Feedback: too harsh, not as gutteral

**Comment by silmist** [comment]
Customer SFX folder: https://drive.google.com/drive/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j?usp=share_link 

- sfx_BirdBadReact01_AnnieZhang
- sfx_BirdBadReact02_AnnieZhang
- sfx_BirdGoodReact01.2_AnnieZhang
- sfx_BirdGoodReact02.2_AnnieZhang
