### ISSUE TITLE
Morning Driving Music Final Asset Development

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#279]
Polish and further develop the music track for the Morning driving portion of the game based on the pre-existing concept tracks.

Early Dawn

- Faster, urgent, racing, enthusiastic
- Excitement
- Fast and chaotic
- Around 200 BPM

More Detailed Style Guide: https://docs.google.com/document/d/1p4Xf0tNKXjxx3Vr1wMnoqeqkMLU6nXwcayTMTyNxzuM/edit?usp=sharing
Concept tracks found here: [https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link](https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link)

**Comment by vinhta1** [comment]
[Semi-Final added to drive](https://drive.google.com/file/d/1zgCqKxiRv-1XWZktckSdL3ZllP2qSK1C/view?usp=share_link)
Working Name: (Morning) Scramble
