### ISSUE TITLE
Noon Driving Music Final Asset Development

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#280]
Polish and further develop the music track for the noon driving portion of the game based on the pre-existing concept tracks.

Noon

- on the roll, fresh perspective
- Confidence, in the groove of things
- Slows down but keeps the same level of intensity
- Time is moving, though...

More Detailed Style Guide: https://docs.google.com/document/d/1p4Xf0tNKXjxx3Vr1wMnoqeqkMLU6nXwcayTMTyNxzuM/edit?usp=sharing
Concept tracks found here: [https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link](https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link)

**Comment by vinhta1** [comment]
latest Noon track version: https://discord.com/channels/1050526588514598942/1073492504604839956/1105710397576708097

**Comment by vinhta1** [comment]
Moved old noon to prehistoric
[Added latest noon track to drive](https://drive.google.com/file/d/1tjPVL4wtwY3ih6TEsmXM-gNN7D4pVi4p/view?usp=sharing)
Working name: Flipping Tacos and Trucks

**Comment by vinhta1** [comment]
[Semi-final](https://drive.google.com/file/d/1igcXkSLN6HJPhvPfSscLf05VDkVOR2hs/view?usp=sharing)
