### ISSUE TITLE
Afternoon/Dusk Driving Music Final Asset Development

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#282]
Polish and further develop the music track for the afternoon/dusk driving portion of the game based on the pre-existing concept tracks.

Afternoon/Dusk

- Ticking-clock, anxiety, desperation, weary
- Hint that your time is up 
- Easy to transition into the silence of the bad ending/night driving

More Detailed Style Guide: https://docs.google.com/document/d/1p4Xf0tNKXjxx3Vr1wMnoqeqkMLU6nXwcayTMTyNxzuM/edit?usp=sharing
Concept tracks found here: [https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link](https://drive.google.com/drive/folders/1Rf0j16bmrkFvIahoJ0OQGT1ZkGKxCE8u?usp=share_link)

**Comment by vinhta1** [comment]
latest evening/dusk: https://discord.com/channels/1050526588514598942/1073492504604839956/1105709209619791882

**Comment by vinhta1** [comment]
moved old evening/dusk to prehistoric
[Added latest version of Evening to drive HEAVY WIP](https://drive.google.com/file/d/1mSOaanb-5Wl2OpAIvo_pcZjANqW-UL6i/view?usp=sharing)
Working Name: Floor It

**Comment by vinhta1** [comment]
[Semi-final](https://drive.google.com/file/d/1cu-eVQIfc0g8miCAl0OWhIZB_cbo2d_2/view?usp=sharing)
