### ISSUE TITLE
City Ambience (Driving)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#288]
Driving SFX Folder: https://drive.google.com/drive/folders/18LJnK-7HCsLu2p1BKaGfPW0A_So0qr5f?usp=share_link

Provide some city ambience that SUBTLY plays in the background of the game (a siren or distant honk). We have crickets and city white noise, but we need that occasional beep, screech, etc.

Please put your asset(s) in the driving sfx folder, and leave a comment with the name and link to your asset(s)

**Comment by JeremyH0451** [comment]
Emergency Vehicle Siren [https://drive.google.com/drive/folders/18LJnK-7HCsLu2p1BKaGfPW0A_So0qr5f?usp=share_link](https://drive.google.com/drive/folders/18LJnK-7HCsLu2p1BKaGfPW0A_So0qr5f?usp=share_link)

**Comment by Irkedibis** [comment]
Sounds good, work on bank organization so ambience = ambience
