### ISSUE TITLE
Driving Music Concept

### ISSUE THREAD

**Issue by sweetautumndeer** [GDACollab/TacoCat#38]
Single motif presented in different ways as the day turns to night. Eventually going to be 4 distinct tracks.

Style Guide: https://docs.google.com/document/d/1R2i_TjMr9fab4DJrdDIlw2lI8va4kjZ0dWQUF1NP3CM/edit?usp=sharing

**Comment by Irkedibis** [comment]
Current iteration called "mus_DuskDrivingConcept01e_VinhTa":
https://drive.google.com/file/d/1OF5CeqZEgew4geg81nHjRo4UZrDHKa_D/view?usp=share_link
