### ISSUE TITLE
Main Menu Music Concept

### ISSUE THREAD

**Issue by sweetautumndeer** [GDACollab/TacoCat#39]
Style Guide: https://docs.google.com/document/d/1R2i_TjMr9fab4DJrdDIlw2lI8va4kjZ0dWQUF1NP3CM/edit?usp=sharing

**Comment by Irkedibis** [comment]
Using Vinh's concept track, renamed "mus_MainMenu01_VinhTa":
https://drive.google.com/file/d/1_eBo1E-Ux454qcEtfi-yyLqhLSsLPuGn/view?usp=share_link
