### ISSUE TITLE
Reference Tracks Doc

### ISSUE THREAD

**Issue by gold-mari** [GDACollab/TacoCat#7]
Get a document for music reference tracks for Taco Cat!
[Example document from last year](https://docs.google.com/document/d/1ZAwIfjNAF5_gGOLUjyIyHn4oyVqrF7TlzpEMxbJKIps/edit#heading=h.lr9fxf1w92mh)

**Comment by vinhta1** [comment]
[Reference Tracks - Sound](https://docs.google.com/document/d/1JSjzH8wE4IJRplg6qd8-3ro91DqOIPjnKJWpBGAB2j0/edit?usp=sharing)
