### ISSUE TITLE
OUTDATED | SFX Concepts (Driving)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#86]
Long-term task dedicated to SFX for the **driving** section.

Update with:
- A comment on what you made/added
- A link to find and hear your sounds
- who to ask for review (could be me (optimalystic), another member, another department, etc)

SFX list: https://docs.google.com/spreadsheets/d/1p6o-WQsl1Hy2EW_-neKIY4pfV3HE_lr5xGYMFvKN7fs/edit#gid=0

**Comment by JeremyH0451** [comment]
The current iterations of the car start and driving sounds.

Car start/ignition: [https://drive.google.com/file/d/10N8tcG-e77Ax3KDf9vwyMhGghu_rmfwn/view?usp=share_link](https://drive.google.com/file/d/10N8tcG-e77Ax3KDf9vwyMhGghu_rmfwn/view?usp=share_link)
Driving 1: [https://drive.google.com/file/d/1J29V4PDJZL3N7fN_PAOGFgJ_Aj38ucAJ/view?usp=share_link](https://drive.google.com/file/d/1J29V4PDJZL3N7fN_PAOGFgJ_Aj38ucAJ/view?usp=share_link)
Driving 2: [https://drive.google.com/file/d/1tmYqQhnyacbX0a9JYbm0dTlhWCIVaXAz/view?usp=share_link](https://drive.google.com/file/d/1tmYqQhnyacbX0a9JYbm0dTlhWCIVaXAz/view?usp=share_link)

**Comment by ErdrickBelmont** [comment]
Created  

- a two cylinder sounding engine noise: https://drive.google.com/file/d/17VYgZGpN3LoWEW65s_6RiIaH3LmyEalJ/view?usp=share_link
- A sound of the truck crashing: https://drive.google.com/file/d/1yCGWHcsiIoblg_HKXfggVa6JClsDwybz/view?usp=share_link
- and a low on gas sound affect: https://drive.google.com/file/d/1oUtEilsRPcBeFdagytalunWW5tWY6FE8/view?usp=share_link

**Comment by Irkedibis** [comment]
[link](https://drive.google.com/drive/folders/18LJnK-7HCsLu2p1BKaGfPW0A_So0qr5f?usp=sharing)

Added
- Nitro Boost | "sfx_nitroBoostv1_JacksonRichmond"
