### ISSUE TITLE
OUTDATED | SFX Concepts (Taco Making)

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#87]
Long-term task dedicated to SFX for the **taco making** section.

Update with:
- A comment on what you added
- A link to find and hear your sounds
- Who (person/department) to ask for review

SFX list: https://docs.google.com/document/d/1CG7GRmBYwaBgKXKEJkOGJuu1YsbcvOvcrLMQh1K7jBk/edit?usp=share_link

**Comment by vinhta1** [comment]
https://drive.google.com/drive/folders/1lqJIZkNbCowjr0Yymsz9FZgivqx9TmW-?usp=sharing
Added
- Fish
- Sour Cream
- Cabbage
- Pico De Gallo

**Comment by cigreen** [comment]
https://drive.google.com/drive/u/2/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j

Added default reactions as well as frog reactions.

**Comment by cigreen** [comment]
https://drive.google.com/drive/u/2/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j 

Added sounds for fish.

**Comment by cigreen** [comment]
https://drive.google.com/drive/u/2/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j

Added sounds for sheep.

**Comment by cigreen** [comment]
https://drive.google.com/drive/u/2/folders/1wZDbdX3yqaH3U7jczBBHb7q3Pr8REG4j

Updated sheep sounds as well as added a new sheep reaction.
